/********************************************************************************************************************
 * \file MCMCAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2020
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "MCMCAN.h"
#include "LED.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
McmcanType                  g_mcmcan0;                       /* Global MCMCAN configuration and control structure    */
McmcanType                  g_mcmcan1;                       /* Global MCMCAN configuration and control structure    */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro:
 * - defines linker section as .intvec_tc<vector number>_<interrupt priority>.
 * - defines compiler specific attribute for the interrupt functions.
 * - defines the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(can0IsrTxHandler, 0, ISR_PRIORITY_CAN0_TX);
IFX_INTERRUPT(can0IsrRxHandler, 0, ISR_PRIORITY_CAN0_RX);
IFX_INTERRUPT(can1IsrTxHandler, 0, ISR_PRIORITY_CAN1_TX);
IFX_INTERRUPT(can1IsrRxHandler, 0, ISR_PRIORITY_CAN1_RX);

/* Interrupt Service Routine (ISR) called once the TX interrupt has been generated.
 * Turns on the LED1 to indicate successful CAN message transmission.
 */
void can0IsrTxHandler(void)
{
    /* Clear the "Transmission Completed" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan0.canSrcNode.node, IfxCan_Interrupt_transmissionCompleted);
}

/* Interrupt Service Routine (ISR) called once the RX interrupt has been generated.
 * Compares the content of the received CAN message with the content of the transmitted CAN message
 * and in case of success, toggles an LED to indicate successful CAN message reception.
 */
void can0IsrRxHandler(void)
{
    /* Clear the "Message stored to Dedicated RX Buffer" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan0.canDstNode.node, IfxCan_Interrupt_messageStoredToDedicatedRxBuffer);

    /* Read the received CAN message */
    IfxCan_Can_readMessage(&g_mcmcan0.canDstNode, &g_mcmcan0.rxMsg, g_mcmcan0.rxData);

    /* Check if the received data matches with the transmitted one */
    if( ( g_mcmcan0.rxData[0] == g_mcmcan0.txData[0] ) &&
        ( g_mcmcan0.rxData[1] == g_mcmcan0.txData[1] ) &&
        ( g_mcmcan0.rxMsg.messageId == g_mcmcan0.txMsg.messageId ) )
    {
        /* Toggle an LED to indicate correctness of the received message */
        toggleLED4();
    }
}

/* Interrupt Service Routine (ISR) called once the TX interrupt has been generated.
 */
void can1IsrTxHandler(void)
{
    /* Clear the "Transmission Completed" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan1.canSrcNode.node, IfxCan_Interrupt_transmissionCompleted);
}

/* Interrupt Service Routine (ISR) called once the RX interrupt has been generated.
 * Compares the content of the received CAN message with the content of the transmitted CAN message
 */
void can1IsrRxHandler(void)
{
    /* Clear the "Message stored to Dedicated RX Buffer" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan1.canDstNode.node, IfxCan_Interrupt_messageStoredToDedicatedRxBuffer);

    /* Read the received CAN message */
    IfxCan_Can_readMessage(&g_mcmcan1.canDstNode, &g_mcmcan1.rxMsg, g_mcmcan1.rxData);
    /* Toggle an LED to indicate received message */
    toggleLED2();

    /* Echo the same message back out */
    IfxCan_Can_sendMessage(&g_mcmcan1.canSrcNode, &g_mcmcan1.rxMsg, g_mcmcan1.rxData);
    /* Just to indicate that the CAN message has been transmitted by toggling an LED */
    toggleLED3();
}

/* Function to initialize MCMCAN module 0 and nodes related for this application use case */
void initMcmcan0(void)
{
    /* ==========================================================================================
     * CAN 0 module configuration and initialization:
     * ==========================================================================================
     *  - load default CAN module configuration into configuration structure
     *  - initialize CAN module with the default configuration
     * ==========================================================================================
     */
    IfxCan_Can_initModuleConfig(&g_mcmcan0.canConfig, &MODULE_CAN0);

    IfxCan_Can_initModule(&g_mcmcan0.canModule, &g_mcmcan0.canConfig);

    /* ==========================================================================================
     * Source CAN node configuration and initialization:
     * ==========================================================================================
     *  - load default CAN node configuration into configuration structure
     *
     *  - assign source CAN node to CAN node 0
     *
     *  - define the frame to be the transmit and receive
     *
     *  - once the transmission is completed, raise the interrupt
     *  - define the transmission complete interrupt priority
     *  - assign the interrupt line 0 to the transmission complete interrupt
     *  - transmission complete interrupt service routine should be serviced by the CPU0
     *  - configure pins to use header on Triboard
     *  - initialize the source CAN node with the modified configuration
     * ==========================================================================================
     */
    IfxCan_Can_initNodeConfig(&g_mcmcan0.canNodeConfig, &g_mcmcan0.canModule);

    g_mcmcan0.canNodeConfig.busLoopbackEnabled = FALSE;
    g_mcmcan0.canNodeConfig.nodeId = IfxCan_NodeId_0;
    g_mcmcan0.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;

    g_mcmcan0.canNodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;
    g_mcmcan0.canNodeConfig.interruptConfig.traco.priority = ISR_PRIORITY_CAN0_TX;
    g_mcmcan0.canNodeConfig.interruptConfig.traco.interruptLine = IfxCan_InterruptLine_0;
    g_mcmcan0.canNodeConfig.interruptConfig.traco.typeOfService = IfxSrc_Tos_cpu0;

//explicitly specify messagRAM.baseaddress due to a bug in iLLD
    g_mcmcan1.canNodeConfig.messageRAM.baseAddress = (uint32)&MODULE_CAN0;

// set up pins for CAN0 Node 0
    IfxCan_Can_Pins pinsCAN00;
    pinsCAN00.rxPin = &IfxCan_RXD00B_P20_7_IN;
    pinsCAN00.rxPinMode = IfxPort_InputMode_pullUp;
    pinsCAN00.txPin = &IfxCan_TXD00_P20_8_OUT;
    pinsCAN00.txPinMode = IfxPort_OutputMode_pushPull;
    pinsCAN00.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed2;
    g_mcmcan0.canNodeConfig.pins = &pinsCAN00;

    IfxCan_Can_initNode(&g_mcmcan0.canSrcNode, &g_mcmcan0.canNodeConfig);

    /* ==========================================================================================
     * Destination CAN node configuration and initialization:
     * ==========================================================================================
     *  - Reuse the configuration structure from the Tx configuration
     *
     *  - once the message is stored in the dedicated RX buffer, raise the interrupt
     *  - define the receive interrupt priority
     *  - assign the interrupt line 1 to the receive interrupt
     *  - receive interrupt service routine should be serviced by the CPU0
     *
     *  - initialize the destination CAN node with the modified configuration
     * ==========================================================================================
     */

    /* Everything else is the same as Tx node. Just configure the interrupt */
    g_mcmcan0.canNodeConfig.interruptConfig.messageStoredToDedicatedRxBufferEnabled = TRUE;
    g_mcmcan0.canNodeConfig.interruptConfig.reint.priority = ISR_PRIORITY_CAN0_RX;
    g_mcmcan0.canNodeConfig.interruptConfig.reint.interruptLine = IfxCan_InterruptLine_1;
    g_mcmcan0.canNodeConfig.interruptConfig.reint.typeOfService = IfxSrc_Tos_cpu0;

    IfxCan_Can_initNode(&g_mcmcan0.canDstNode, &g_mcmcan0.canNodeConfig);


    /* ==========================================================================================
     * CAN filter configuration and initialization:
     * ==========================================================================================
     *  - filter configuration is stored under the filter element number 0
     *  - store received frame in a dedicated RX Buffer
     *  - define the same message ID as defined for the TX message
     *  - assign the filter to the dedicated RX Buffer (RxBuffer0 in this case)
     *
     *  - initialize the standard filter with the modified configuration
     * ==========================================================================================
     */
    g_mcmcan0.canFilter.number = 0;
    g_mcmcan0.canFilter.elementConfiguration = IfxCan_FilterElementConfiguration_storeInRxBuffer;
    g_mcmcan0.canFilter.id1 = CAN0_MESSAGE_ID;
    g_mcmcan0.canFilter.rxBufferOffset = IfxCan_RxBufferId_0;

    IfxCan_Can_setStandardFilter(&g_mcmcan0.canDstNode, &g_mcmcan0.canFilter);

    /* Define the content of the data to be transmitted */
    g_mcmcan0.txData[0] = TX_DATA_LOW_WORD;
    g_mcmcan0.txData[1] = TX_DATA_HIGH_WORD;
}

/* Function to initialize MCMCAN module 1 and nodes related for this application use case */
void initMcmcan1(void)
{
    /* ==========================================================================================
     * CAN 0 module configuration and initialization:
     * ==========================================================================================
     *  - load default CAN module configuration into configuration structure
     *  - initialize CAN module with the default configuration
     * ==========================================================================================
     */
    IfxCan_Can_initModuleConfig(&g_mcmcan1.canConfig, &MODULE_CAN1);

    IfxCan_Can_initModule(&g_mcmcan1.canModule, &g_mcmcan1.canConfig);

    /* ==========================================================================================
     * Source CAN node configuration and initialization:
     * ==========================================================================================
     *  - load default CAN node configuration into configuration structure
     *
     *  - assign source CAN node to CAN node 0
     *
     *  - define the frame to be the transmit and receive
     *
     *  - once the transmission is completed, raise the interrupt
     *  - define the transmission complete interrupt priority
     *  - assign the interrupt line 0 to the transmission complete interrupt
     *  - transmission complete interrupt service routine should be serviced by the CPU0
     *  - configure pins to use header on Triboard
     *  - initialize the source CAN node with the modified configuration
     * ==========================================================================================
     */
    IfxCan_Can_initNodeConfig(&g_mcmcan1.canNodeConfig, &g_mcmcan1.canModule);

    g_mcmcan1.canNodeConfig.busLoopbackEnabled = FALSE;
    g_mcmcan1.canNodeConfig.nodeId = IfxCan_NodeId_0;
    g_mcmcan1.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;

    g_mcmcan1.canNodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;
    g_mcmcan1.canNodeConfig.interruptConfig.traco.priority = ISR_PRIORITY_CAN1_TX;
    g_mcmcan1.canNodeConfig.interruptConfig.traco.interruptLine = IfxCan_InterruptLine_0;
    g_mcmcan1.canNodeConfig.interruptConfig.traco.typeOfService = IfxSrc_Tos_cpu0;

//explicitly specify messagRAM.baseaddress due to a bug in iLLD
    g_mcmcan1.canNodeConfig.messageRAM.baseAddress = (uint32)&MODULE_CAN1;

// set up pins for CAN1 node 0
    IfxCan_Can_Pins pinsCAN10;
    pinsCAN10.rxPin = &IfxCan_RXD10C_P23_0_IN;
    pinsCAN10.rxPinMode = IfxPort_InputMode_pullUp;
    pinsCAN10.txPin = &IfxCan_TXD10_P23_1_OUT;
    pinsCAN10.txPinMode = IfxPort_OutputMode_pushPull;
    pinsCAN10.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed2;
    g_mcmcan1.canNodeConfig.pins = &pinsCAN10;

    IfxCan_Can_initNode(&g_mcmcan1.canSrcNode, &g_mcmcan1.canNodeConfig);

    /* ==========================================================================================
     * Destination CAN node configuration and initialization:
     * ==========================================================================================
     *  - Reuse the configuration structure from the Tx configuration
     *
     *  - once the message is stored in the dedicated RX buffer, raise the interrupt
     *  - define the receive interrupt priority
     *  - assign the interrupt line 1 to the receive interrupt
     *  - receive interrupt service routine should be serviced by the CPU0
     *
     *  - initialize the destination CAN node with the modified configuration
     * ==========================================================================================
     */

    /* Everything else is the same as Tx node. Just configure the interrupt */
    g_mcmcan1.canNodeConfig.interruptConfig.messageStoredToDedicatedRxBufferEnabled = TRUE;
    g_mcmcan1.canNodeConfig.interruptConfig.reint.priority = ISR_PRIORITY_CAN1_RX;
    g_mcmcan1.canNodeConfig.interruptConfig.reint.interruptLine = IfxCan_InterruptLine_1;
    g_mcmcan1.canNodeConfig.interruptConfig.reint.typeOfService = IfxSrc_Tos_cpu0;

    IfxCan_Can_initNode(&g_mcmcan1.canDstNode, &g_mcmcan1.canNodeConfig);


    /* ==========================================================================================
     * CAN filter configuration and initialization:
     * ==========================================================================================
     *  - filter configuration is stored under the filter element number 0
     *  - store received frame in a dedicated RX Buffer
     *  - define the same message ID as defined for the TX message
     *  - assign the filter to the dedicated RX Buffer (RxBuffer0 in this case)
     *
     *  - initialize the standard filter with the modified configuration
     * ==========================================================================================
     */
    g_mcmcan1.canFilter.number = 0;
    g_mcmcan1.canFilter.elementConfiguration = IfxCan_FilterElementConfiguration_storeInRxBuffer;
    g_mcmcan1.canFilter.id1 = CAN0_MESSAGE_ID;
    g_mcmcan1.canFilter.rxBufferOffset = IfxCan_RxBufferId_0;

    IfxCan_Can_setStandardFilter(&g_mcmcan1.canDstNode, &g_mcmcan1.canFilter);
}

/* Function to initialize both TX and RX messages with the default data values.
 * After initialization of the messages, the TX message is transmitted.
 */
void transmitCanMessage_CAN0(void)
{
    /* Initialization of the RX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan0.rxMsg);
    /* Invalidation of the RX message data content */
    memset((void *)(&g_mcmcan0.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));

    /* Initialization of the TX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan0.txMsg);

//    /* Define the content of the data to be transmitted */
//    g_mcmcan0.txData[0] = TX_DATA_LOW_WORD;
//    g_mcmcan0.txData[1] = TX_DATA_HIGH_WORD;
    /* Modify the content of the data to be transmitted at each cycle */
    g_mcmcan0.txData[0] += 1;
    g_mcmcan0.txData[1] += 1;

    /* Set the message ID that is used during the receive acceptance phase */
    g_mcmcan0.txMsg.messageId = CAN0_MESSAGE_ID;

    /* Send the CAN message with the previously defined TX message content */
    while( IfxCan_Status_notSentBusy ==
           IfxCan_Can_sendMessage(&g_mcmcan0.canSrcNode, &g_mcmcan0.txMsg, &g_mcmcan0.txData[0]) )
    {
    }

    /* Just to indicate that the CAN message has been transmitted by toggling an LED */
    toggleLED1();
}

/*
 * This function is unused in the example, but provided for consistency
 */
void transmitCanMessage_CAN1(void)
{
    /* Initialization of the RX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan1.rxMsg);

    /* Invalidation of the RX message data content */
    memset((void *)(&g_mcmcan1.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));

    /* Initialization of the TX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan1.txMsg);

    /* Define the content of the data to be transmitted */
    g_mcmcan1.txData[0] = TX_DATA_LOW_WORD;
    g_mcmcan1.txData[1] = TX_DATA_HIGH_WORD;

    /* Set the message ID that is used during the receive acceptance phase */
    g_mcmcan1.txMsg.messageId = CAN1_MESSAGE_ID;

    /* Send the CAN message with the previously defined TX message content */
    while( IfxCan_Status_notSentBusy ==
           IfxCan_Can_sendMessage(&g_mcmcan1.canSrcNode, &g_mcmcan1.txMsg, &g_mcmcan1.txData[0]) )
    {
    }
}

